#!/bin/bash

ORMLITE_DATA="http://ormlite.com/releases/4.27/ormlite-core-4.27.jar"
ORMLITE_FETCHURL="http://ormlite.com/releases"
PACKAGES="ormlite-core ormlite-android"

if [[ $# -ne 1 ]]; then
	echo "usage: upgrade-ormlite [new version]"
	exit 1
fi

oldversion=$(ls lib/*.jar | grep -oP '\d+\.\d+' | head -n 1)

if [[ "$1" == "$oldversion" ]]; then
	echo "Already at version $1"
	exit 1
fi

echo "Old version is $oldversion"

svn rm --force lib/ormlite-*$oldversion*.jar

for P in $PACKAGES; do
	base="$P-$1"
	lib="$base.jar"
	javadoc="$base-javadoc.jar"

	wget -nv "$ORMLITE_FETCHURL/$1/$lib" -O lib/$lib || exit 1
	svn add lib/$lib

	wget -nv "$ORMLITE_FETCHURL/$1/$javadoc" -O lib/$javadoc || exit 1
	svn add lib/$javadoc

	sed -i -e "s/$P-$oldversion/$base/" .classpath
done

