#!/bin/bash

source "$(dirname $_)/shared.sh" || exit 1

if [[ $# -eq 0 ]]; then
	BASENAME=bak_$(date +%Y-%m-%d)
else
	BASENAME="$1"
fi

[[ ! -e "$BASENAME.sqlite" && ! -e "$BASENAME.config" ]] || die "Refusing to overwrite $BASENAME"

#TEMPDB="$DTEMP/.rxdroid-db.sqlite"
DB="/data/data/$PKG/databases/db.sqlite"
CFG="/data/data/$PKG/shared_prefs/${PKG}_preferences.xml"

#echo -n "Copying database to temporary location ... "
#run adb-shell "su -c 'cp /data/data/$PKG/databases/db.sqlite $TEMPDB'"
#echo "done"

echo -n "Pulling database from device ... "
adb-pull $DB "$BASENAME.sqlite"

echo -n "Pulling configuration from device ... "
adb-pull $CFG "$BASENAME.config"

exit 0

#echo -n "Removing database at temporary location ... "
#run adb-shell "su -c 'rm $TEMPDB'"
#echo "done"
