#!/bin/bash


if [[ $# -lt 1 ]]; then
	FILE=db_$(date +%Y-%m-%d).sqlite
else
	FILE="$1"
fi

echo -n "Pulling database from device ... "
adb pull /data/data/at.caspase.rxdroid/databases/db.sqlite "$FILE"

