#!/bin/bash

source "$(dirname $_)/shared.sh"


[[ -f "$1" ]] || die "$1: No such file"

if [[ "$(head -c 6 "$1")" != "SQLite" ]]; then
	die "$1: Not an SQLite database"
fi

DATABASES=/data/data/$PKG/databases
TARGET=$DATABASES/db.sqlite

INFO=`adb shell ls -l /data/data | grep $PKG`
FUID=`awk '{ print $2 }' <<<$INFO`
FGID=`awk '{ print $3 }' <<<$INFO`

echo -n "Remounting data/ ... "
run adb-shell mount -o remount,rw /data
echo "done"

run adb-shell mkdir -p $(dirname $TARGET)

echo -n "Pushing database to device ... "
adb push "$1" $TARGET || die

echo -n "Fixing permissions ... "
run adb-shell chown $FUID.$FGID $DATABASES $DATABASES/"*"
run adb-shell am force-stop $PKG

echo "done"
