#!/bin/bash

if [[ ! -f "$1" ]]; then
	echo "$1: No such file" >&2
	exit 1
fi

if ! grep -i "sqlite" <<< `file -b "$1"`; then
	echo "$1: Not an SQLite database" >&2
	exit 1
fi

PKG=at.caspase.rxdroid
DATABASES=/data/data/$PKG/databases
TARGET=$DATABASES/db.sqlite

INFO=`adb shell ls -l $DATABASES/..`
FUID=`awk '{ print $2 }' <<<$INFO`
FGID=`awk '{ print $3 }' <<<$INFO`

adb push "$1" $TARGET || exit 1
adb shell busybox chown -R $FUID:$FGID $DATABASES  || exit 1
adb shell am kill $PKG || exit 1
