#!/bin/bash

source "$(dirname $_)/shared.sh"

BAKDB=".backup.sqlite"
BAKCFG=".backup.config"
APK="${1:-bin/RxDroid.apk}"

if [[ ! -f "$APK" ]]; then
	die "$APK does not exist"
fi

rm -f "$BAKDB" "$BAKCFG"

scripts/db-backup $BAKDB $BAKCFG || die

echo -n "Removing $PKG ... "
adb uninstall $PKG || die

echo -n "Reinstalling $PKG ... "
adb install $APK || die

scripts/db-restore $BAKDB $BAKCFG || die
rm -f $BAKDB
