#!/bin/bash

source "$(dirname $_)/shared.sh"

BAK=".backup.sqlite"
APK="bin/RxDroid.apk"

scripts/db-backup $BAK || die

echo -n "Removing $PKG ... "
adb uninstall $PKG || die

echo -n "Reinstalling $PKG ... "
adb install $APK || die

scripts/db-restore $BAK || die
rm -f $BAK
