#!/bin/bash

source "$(dirname $_)/shared.sh"

ORMLITE_FETCHURL="http://ormlite.com/releases"
PACKAGES="ormlite-core ormlite-android"

if [[ $# -lt 1 ]]; then
	die "usage: upgrade-ormlite [new version]"
fi

oldversion=`grep -o -m1 -P 'ormlite-android-(\d+\.\d+)' .classpath | awk 'BEGIN { FS="-" }; { print $3 }'`

if [[ "$1" == "$oldversion" ]]; then
	die "Already at version $1"
fi

echo "Old version is $oldversion"


for P in $PACKAGES; do
	base="$P-$1"
	jar="$base.jar"
	#javadoc="$base-javadoc.jar"

	wget -nv "$ORMLITE_FETCHURL/$1/$jar" -O libs/$jar || exit 1
	svn add libs/$lib

	#wget -nv "$ORMLITE_FETCHURL/$1/$javadoc" -O libs/$javadoc || exit 1
	#svn add libs/$javadoc

	sed -i -e "s/$P-$oldversion/$base/" .classpath

done
svn rm --force libs/ormlite-*$oldversion*.jar

if [[ "$2" != "nocommit" ]]; then
	svn ci -m "ORMLite upgrade: $oldversion -> $1"
fi
